import {
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { UserState } from '../../store'

const navigationConfig = (user: UserState): NavigationTree[] => [
  {
    key: 'home',
    path: '/home',
    title: 'Dashboard',
    translateKey: 'Dashboard',
    icon: 'sales',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'academy',
    path: '/academy',
    title: 'Mis Cursos',
    translateKey: 'Mis Cursos',
    icon: 'academy',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER', 'ADMIN'],
    subMenu: [],
  } /* 
  {
    key: 'algorithm-mr-range',
    path: '/algorithm-mr-range',
    title: 'Algoritmo Mr. Rango',
    translateKey: 'nav.dashboard',
    icon: 'algorithmMrRange',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['ALGORITHM', 'ADMIN'],
    subMenu: [],
  }, */,
  // {
  //   key: 'subscriptions',
  //   path: '/subscriptions',
  //   title: 'Comprar Franquicia',
  //   translateKey: 'nav.pay-supreme',
  //   icon: 'memberships',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: [],
  //   subMenu: [
      /* {
        key: 'subscriptions-manual',
        path: `/subscriptions-manual`,
        title: 'Franquicias Manuales',
        translateKey: 'nav.subscriptions-manual',
        icon: 'memberships',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      }, */
      // {
      //   key: 'subscriptions-automatic',
      //   path: `/subscriptions-automatic`,
      //   title: 'Franquicias Automáticas',
      //   translateKey: 'nav.subscriptions-automatic',
      //   icon: 'memberships',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [],
      //   subMenu: [],
      // },
      // {
      //   key: 'subscriptions-product',
      //   path: `/subscriptions-product`,
      //   title: 'Franquicias de Producto',
      //   translateKey: 'nav.subscriptions-product',
      //   icon: 'memberships',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [],
      //   subMenu: [],
      // },
      {
        key: 'subscriptions-digital',
        path: `/subscriptions-digital`,
        title: 'Comprar Membresía',
        translateKey: 'Comprar Membresía',
        icon: 'memberships',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
  //   ],
  // },
  {
    key: 'participations',
    path: '/participations',
    title: 'Participaciones',
    translateKey: 'nav.dashboard',
    icon: 'participationsIcon',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['PARTICIPATIONS'],
    subMenu: [],
  },
  {
    key: 'order-list',
    path: `/order-list`,
    title: 'UNINIVEL',
    translateKey: 'UNINIVEL',
    icon: 'direct-people',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  // {
  //   key: 'my-automatic-franchises',
  //   path: '/my-automatic-franchises',
  //   title: 'Mis Franquicias',
  //   translateKey: 'nav.my-automatic-franchises',
  //   icon: 'memberships',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: ['AUTOMATIC_FRANCHISES'],
  //   subMenu: [],
  // },
  {
    key: 'binary',
    path: `/binary`,
    title: 'Binario',
    translateKey: 'Binario',
    icon: 'binary',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['USER'],
    subMenu: [
      {
        key: 'binary.tree',
        path: `/binary-tree`,
        title: 'Árbol Binario',
        translateKey: 'Árbol Binario',
        icon: 'binary',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['USER'],
        subMenu: [],
      },
      /* {
        key: 'binary.active',
        path: `/binary-active`,
        title: 'Binario Activo',
        translateKey: 'nav.order-list.binary-active',
        icon: 'binary',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['USER'],
        subMenu: [],
      }, */
    ],
  },
  /*{
    key: 'sanguine-map',
    path: `/report-sanguine-map`,
    title: 'Mapa',
    translateKey: 'nav.order-list',
    icon: 'map',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },*/
  // {
  //   key: 'rank',
  //   path: `/rank`,
  //   title: 'Rango',
  //   translateKey: 'nav.order-list',
  //   icon: 'rank',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: ['USER'],
  //   subMenu: [],
  // },
  {
    key: 'user-payroll.history',
    path: `/payroll/history`,
    title: 'Historial de pagos',
    translateKey: 'Historial de pagos',
    icon: 'payroll',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  // {
  //   key: 'marketplace',
  //   path: `/marketplace`,
  //   title: 'Marketplace Productos Créditos',
  //   translateKey: 'nav.order-list',
  //   icon: 'marketplace',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  //   //href: `https://www.empoweritup.com/?user=${user?.uid ?? ''}`,
  // },
  // {
  //   key: 'marketplace-digital-service',
  //   path: `/marketplace-digital-service`,
  //   title: 'Servicios Digitales',
  //   translateKey: 'nav.order-list',
  //   icon: 'digitalService',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: ['USER'],
  //   subMenu: [],
  //   //href: `https://www.empoweritup.com/?user=${user?.uid ?? ''}`,
  // },
  /* {
    key: 'marketplace-distributor',
    path: `/marketplace-distributor`,
    title: 'Marketplace Productos Bono Distribuidor',
    translateKey: 'nav.order-list',
    icon: 'distributorMarketplace',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
    //href: `https://www.empoweritup.com/?user=${user?.uid ?? ''}`,
  }, */
  // {
  //   key: 'marketplace.history',
  //   path: `/marketplace/history`,
  //   title: 'Historial de Créditos',
  //   translateKey: 'nav.order-list',
  //   icon: 'coins',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: ['USER'],
  //   subMenu: [],
  // },
  // {
  //   key: 'mr-money-power.history',
  //   path: `/mr-money-power/history`,
  //   title: 'ADMIN: Historial de Mr. Money Power',
  //   translateKey: 'nav.order-list',
  //   icon: 'bull',
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: ['ADMIN', 'MR-MONEY-POWER'],
  //   subMenu: [],
  // },
  // {
  //   key: 'admin-automatic-franchises',
  //   path: `/admin-automatic-franchises`,
  //   title: 'ADMIN: Franquicias Automáticas',
  //   translateKey: 'nav.order-list',
  //   icon: 'memberships',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: ['ADMIN'],
  //   subMenu: [
  //     {
  //       key: 'admin-automatic-franchises-pay',
  //       path: `/admin-automatic-franchises-pay`,
  //       title: 'Pagar Franquicias Automaticas',
  //       translateKey: 'nav.order-list.automatic-franchises-pay',
  //       icon: 'memberships',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-automatic-franchises-activate-without-volumen',
  //       path: `/admin-automatic-franchises-activate-without-volumen`,
  //       title: 'Activar sin volumen',
  //       translateKey:
  //         'nav.order-list.automatic-franchises-activate-without-volumen',
  //       icon: 'memberships',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-automatic-franchises-activate-with-volumen',
  //       path: `/admin-automatic-franchises-activate-with-volumen`,
  //       title: 'Activar con volumen',
  //       translateKey:
  //         'nav.order-list.automatic-franchises-activate-with-volumen',
  //       icon: 'memberships',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //   ],
  // },
  // {
  //   key: 'admin-credits',
  //   path: `/admin-credits`,
  //   title: 'ADMIN: Créditos',
  //   translateKey: 'nav.order-list',
  //   icon: 'adminCredits',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: ['ADMIN'],
  //   subMenu: [
  //     {
  //       key: 'admin-credits.all',
  //       path: `/admin-credits/all-credits`,
  //       title: 'Créditos Existentes',
  //       translateKey: 'nav.order-list.all-credits',
  //       icon: 'withdraw',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-credits.add-credits',
  //       path: `/admin-credits/add-credits`,
  //       title: 'Agregar Créditos',
  //       translateKey: 'nav.order-list.add-credits',
  //       icon: 'withdraw',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-credits.history-credits',
  //       path: `/admin-credits/history-credits`,
  //       title: 'Historial de Compras',
  //       translateKey: 'nav.order-list.history-credits',
  //       icon: 'withdraw',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //   ],
  // },
  /*{
    key: '5',
    path: `/academy-leadership`,
    title: 'Sistema de liderazgo',
    translateKey: 'nav.order-list',
    icon: 'system',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER', 'STARTER'],
    subMenu: [],
  },*/
  {
    key: 'admin-payroll',
    path: `/admin-payroll`,
    title: 'ADMIN: Pagos',
    translateKey: 'ADMIN: Pagos',
    icon: 'payroll',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN'],
    subMenu: [
      {
        key: 'admin-payroll.withdraw',
        path: `/admin-payroll/withdraw`,
        title: 'Retirar',
        translateKey: 'nav.order-list.withdraw',
        icon: 'withdraw',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-payroll.pays',
        path: `/admin-payroll/pays`,
        title: 'Pagar',
        translateKey: 'nav.order-list.pays',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-payroll.history',
        path: `/admin-payroll/history`,
        title: 'Historial de pagos',
        translateKey: 'nav.order-list.history',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-payroll.income',
        path: `/admin-payroll/income`,
        title: 'Entradas (USDT)',
        translateKey: 'nav.order-list.income',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      // {
      //   key: 'admin-payroll.7-levels',
      //   path: `/admin-payroll/7-levels`,
      //   title: '7 niveles',
      //   translateKey: 'nav.order-list.7-levels',
      //   icon: 'payroll',
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: ['ADMIN'],
      //   subMenu: [],
      // },
      {
        key: 'admin-payroll.history-leaders',
        path: `/admin-payroll/history-leaders`,
        title: 'Desempeños Líderes',
        translateKey: 'nav.order-list.history-leaders',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
    ],
  },
  // {
  //   key: 'admin-participations',
  //   path: `/admin-participations`,
  //   title: 'ADMIN: Participaciones',
  //   translateKey: 'nav.order-list',
  //   icon: 'participationsAdmin',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: ['ADMIN'],
  //   subMenu: [
  //     {
  //       key: 'admin-participations-payroll',
  //       path: `/admin-participations-payroll/pays`,
  //       title: 'Pagar Participaciones',
  //       translateKey: 'nav.order-list.participations-pays',
  //       icon: 'payroll',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-participations-without-volumen',
  //       path: `/admin-participations-without-volumen`,
  //       title: 'Activar Sin Volumen',
  //       translateKey: 'nav.order-list.participations-pays',
  //       icon: 'payroll',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'admin-participations-with-volumen',
  //       path: `/admin-participations-with-volumen`,
  //       title: 'Activar con Volumen',
  //       translateKey: 'nav.order-list.participations-pays',
  //       icon: 'payroll',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //   ],
  // },
  {
    key: 'admin',
    path: `/admin-`,
    title: 'ADMIN: Academia',
    translateKey: 'ADMIN: Academia',
    icon: 'academy',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'EDUCATOR'],
    subMenu: [
      {
        key: 'admin.academy',
        path: `/academy/agregar`,
        title: 'Agregar Curso',
        translateKey: 'nav.videos',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
      {
        key: 'admin.editAcademy',
        path: `/academy/admin-course`,
        title: 'Administrar Cursos',
        translateKey: 'nav.adminCourse',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
    ],
  },
  {
    key: 'admin-liderazgo',
    path: `/admin-liderazgo`,
    title: 'ADMIN: Sistema de Liderazgo',
    translateKey: 'ADMIN: Sistema de Liderazgo',
    icon: 'system',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'EDUCATOR'],
    subMenu: [
      {
        key: 'admin.leadership',
        path: `/academy-leadership/agregar`,
        title: 'Agregar Curso',
        translateKey: 'nav.videos',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
      {
        key: 'admin.editLeadership',
        path: `/academy-leadership/admin-course`,
        title: 'Administrar Cursos',
        translateKey: 'nav.adminCourse',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
    ],
  },
  {
    key: 'users-admin',
    path: `/users-admin`,
    title: 'ADMIN: Usuarios',
    translateKey: 'ADMIN: Usuarios',
    icon: 'users',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'SUPPORT'],
    subMenu: [
      {
        key: 'report-earnings',
        path: `/report-earnings`,
        title: 'TOP Ganancias Mensuales',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'report-referrals',
        path: `/report-referrals`,
        title: 'TOP Inscripciones Directas',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'report-map',
        path: `/report-map`,
        title: 'Mapa De Usuarios',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-register',
        path: `/admin-register`,
        title: 'Activar sin volumen',
        translateKey: 'nav.order-list',
        icon: 'pencil',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-volumen-register',
        path: `/admin-volumen-register`,
        title: 'Activar con volumen',
        translateKey: 'nav.order-list',
        icon: 'pencil',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'payments-history',
        path: `/payments-history`,
        title: 'Historial de registro/pagos',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'search-users',
        path: `/search-users`,
        title: 'Buscar usuarios',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'enter-as-user',
        path: `/admin/enter-as-user`,
        title: 'Entrar como otro usuario',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'SUPPORT'],
        subMenu: [],
      },
    ],
  },
  // {
  //   key: 'users-ships',
  //   path: `/users-ships`,
  //   title: 'ADMIN: Pedidos',
  //   translateKey: 'nav.order-list',
  //   icon: 'pack',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: ['ADMIN'],
  //   subMenu: [
  //     {
  //       key: 'pending-ships',
  //       path: `/admin/pending-ships`,
  //       title: 'Productos',
  //       translateKey: 'nav.order-list',
  //       icon: 'pack',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //     {
  //       key: 'pending-found',
  //       path: `/admin/pending-fund-account`,
  //       title: 'Cuentas de fondeo',
  //       translateKey: 'nav.order-list',
  //       icon: 'pack',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN'],
  //       subMenu: [],
  //     },
  //   ],
  // }
  
  /* 
  {
    key: 'admin-mr-range',
    path: `/admin/mr-range`,
    title: 'ADMIN: Mr. Rango',
    translateKey: 'nav.order-list',
    icon: 'algorithmMrRange',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'MR-RANGE'],
    subMenu: [
      {
        key: 'admin-mr-range',
        path: `/admin/mr-range-history`,
        title: 'Historial de Licencias',
        translateKey: 'nav.order-list',
        icon: 'algorithmMrRange',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'MR-RANGE'],
        subMenu: [],
      },
    ],
  }, */
  // {
  //   key: 'admin-signals',
  //   path: `/admin/signals`,
  //   title: 'ADMIN: Signals',
  //   translateKey: 'ADMIN: Signals',
  //   icon: '',
  //   type: NAV_ITEM_TYPE_COLLAPSE,
  //   authority: ['ADMIN', 'TRADER'],
  //   subMenu: [
  //     {
  //       key: 'admin-signals-add',
  //       path: `/admin/signals/add`,
  //       title: 'Añadir señales',
  //       translateKey: 'nav.order-list',
  //       icon: 'algorithmMrRange',
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: ['ADMIN', 'TRADER'],
  //       subMenu: [],
  //     },
  //   ],
  // },
]

export default navigationConfig
